### PR TITLE
Fix Issue #4265 - New keywords not available in f:ajax

### LINKED ISSUE #4265: New Component Search Expression keywords are not available in f:ajax when they are the only target
The AjaxBehavior object attempts to reduce memory consumption for single-target values by keeping static lists in memory for the "@all", "@form", "@this", and "@none" keywords. However, it does not account for the newly added keywords (i.e. "@parent") in this mode.  For example, the first ajax behavior in the following example causes an exception while the second one is fine:

```xhtml
<h:inputText ...>
    <f:ajax render="@parent" />
    <f:ajax render="@parent @this" />
</h:inputText>
```

This appears to be because of an old check in AjaxBehavior#toSingletonList(...) that immediately threw an error if an unrecognized keyword was entered.

### PR DESCRIPTION
**Pull request by Toberumono**
This fixes #4265. The fix is fairly minimal. Theoretically, depending on how often some of the new keywords are used (i.e. @parent), additional static arrays might be useful.

Note: This pull request is the corrected version of Pull request #4266.

### CODE REVIEW

**Comment by xinyuan-zhang** [comment]
Hi @arjantijms what do you think of that?

**Comment by Toberumono** [comment]
Unless I am missing something, at present there is no API method for getting the loaded SearchKeywordResolvers, nor is there an API method for determining whether a SearchKeywordResolver that can resolve a given keyword exists. Furthermore, unless I misread the SearchKeywordResolver specification, it is possible for a SearchKeywordResolver instance to change what keywords it resolves based on the SearchExpressionContext (i.e. a SearchKeywordResolver that reads resolvers from the Request, View, or Session scope), therefore, we cannot conclusively determine whether a keyword exists before the final evaluation of the expression. Thus, any warning would require us to assume the use of ApplicationImpl and would be prone to false positives.

My boss submitted the OCA for the company today, so I should be set on that front.

**Comment by BalusC** [comment]
Perhaps you took Arjan's comment too literally. The part "iterating over the SearchKeywordResolver" can be done as below:
```
boolean validKeyword = facesContext
    .getApplication()
    .getSearchKeywordResolver()
    .isResolverForKeyword(searchContext, keyword);
```
Where `keyword` string doesn't have the `@` prefix. E.g. `this`, `parent`, `thiz`, etc.

**Comment by Toberumono** [comment]
@BalusC Thank you for the pointer. I did spend a bit more time than necessary on the iteration part. Unfortunately, the latter issue that I raised (the false positives one) does still apply. A false positive can be created with a pretty simple setup. The relevant code is as follows (I'd ordinarily go with clientId rather than put the components in a map, but, using the component makes for shorter code here):

```java
public class ViewScopedSearchKeywordResolver extends SearchKeywordResolver {

    @Override
    public boolean isResolverForKeyword(SearchExpressionContext searchExpressionContext, String keyword) {
        Map<String, Object> viewMap = FacesContext.getCurrentInstance().getViewRoot().getViewMap();
        Map<String, UIComponent> viewScopedKeywords = (Map<String, UIComponent>) viewMap.get("viewScopedKeywords");
        return viewScopedKeywords != null && viewScopedKeywords.containsKey(keyword);
    }

    @Override
    public void resolve(SearchKeywordContext searchKeywordContext, UIComponent current, String keyword) {
        Map<String, Object> viewMap = FacesContext.getCurrentInstance().getViewRoot().getViewMap();
        Map<String, UIComponent> viewScopedKeywords = (Map<String, UIComponent>) viewMap.get("viewScopedKeywords");
        searchKeywordContext.invokeContextCallback(viewScopedKeywords.get(keyword));
    }
}
```
Create a JSF tag (for this example, we'll go with foo:bar) and, in a render method for foo:bar method for some tag (we'll go with encodeEnd in this case, but the precise method doesn't actually matter - it just has to be a rendering-phase method), do something like this:
```java
public void encodeEnd(FacesContext ctx) throws IOException {
    super.encodeEnd(ctx);

    Map<String, Object> viewMap = FacesContext.getCurrentInstance().getViewRoot().getViewMap();
    Map<String, UIComponent> viewScopedKeywords = (Map<String, UIComponent>) viewMap.get("viewScopedKeywords");
    if (viewScopedKeywords == null) {
        viewMap.put("viewScopedKeywords", viewScopedKeywords = new HashMap<>());
    }
    viewScopedKeywords.put("foobar", this);
}
```

And, in a JSF page:
```xhtml
<!-- Some tags -->
<h:commandButton value="Click me!">
	<f:ajax render="@foobar" /> <!-- This will say that @foobar is an invalid keyword -->
</h:commandButton>
<foo:bar ...>
	<!-- Some tags can go here - it doesn't actually matter -->
</foo:bar>
<!-- Some more tags -->
```
Note that the actual tags don't matter - only that the `f:ajax` tag is before the `foo:bar` tag in the tree.

When you load the page, the `f:ajax` tag will read in the render attribute, and immediately try to validate it. The validation will be unable to find the `@foobar` keyword because it does not exist at that point. However, because the component tree is built before components are targeted for execution and rendering, by the time the components identified by the render attribute are resolved, the keyword will be valid.

**Comment by BalusC** [comment]
I'm not sure. Keywords are in first place intended to be applicationwide constants.

**Comment by tandraschko** [comment]
To fix that problem, the fix is enough.
The statics are just a performance shortcut to skip new list instances for the common keywords. Of course you could create new statics for each keyword but the benefit is minimal and just a improvement.

**Comment by tandraschko** [comment]
PLUS: the searchexpressionresolver will be called when rendering, so there should be already a validation.

**Pull request merged**
