### PR TITLE
Fall back to Java SE ServiceLoader API when Mojarra ServiceFactory fails in order to make Mojarra SPIs compatible with OSGi

### PR DESCRIPTION
**Pull request by stiemannkj1**

### CODE REVIEW

**Comment by arjantijms** [comment]
@stiemannkj1 Thanks for this work, although the version ranges for the `javax.annotation` packages causes an error in Payara:

```
missing requirement [org.glassfish.main.web.weld-integration [51](R 51.0)] osgi.wiring.package; (&(osgi.wiring.package=com.sun.faces.spi)(version>=2.3.0)(!(version>=3.0.0))) [caused by: Unable to resolve org.glassfish.javax.faces [351](R 351.0): 

missing requirement [org.glassfish.javax.faces [351](R 351.0)] osgi.wiring.package; (&(osgi.wiring.package=javax.annotation.processing)(version>=1.0.0)(!(version>=2.0.0)))]]] 
```

**Comment by stiemannkj1** [comment]
@arjantijms, oops sorry, would changing the version for `master` to `[2.0.0, 3.0.0)` fix things?

**Comment by stiemannkj1** [comment]
@arjantijms, I'll look at this today and see what version was generated (automatically) before this commit and try to fix this.

**Comment by arjantijms** [comment]
>oops sorry, would changing the version for master to [2.0.0, 3.0.0) fix things?

I'll try that too, just removing the range works for sure. Thx!

**Comment by arjantijms** [comment]
I haven't checked `2.2.x` yet (Payara 4), might be the same problem. I checked with `master` (Payara 5). At the moment there's no version of Payara using `2.3.x`. I expect though that GF5 has the same issue, which does uses `2.3.x`.

**Comment by stiemannkj1** [comment]
@arjantijms, okay great, I tested everything on `2.2.x` with GlassFish before committing, so it seems like we should be safe there. I assumed that meant that the forward port wouldn't cause issues :( my mistake. I'll test with `2.3.x` on GlassFish 5.x and try to fix.

**Comment by stiemannkj1** [comment]
@arjantijms, hmm I couldn't reproduce the issue with GlassFish `5.0` and Mojarra `2.3.x`. I'll try building the latest Mojarra `master` and see if that reproduces the issue. Does the issue occur on startup or when a webapp is deployed or when a webapp is run? I tried all 3 by running the `javaee6web` tests, but I got no errors and no log messages like the one you posted.

**Comment by stiemannkj1** [comment]
@arjantijms, okay, I was able to reproduce on GF 5.0 with Mojarra `2.4.x`. Looking into it.

**Comment by arjantijms** [comment]
@stiemannkj1 Okay, interesting that it can be reproduced on Mojarra `2.4.x`. What method did you use to build `2.3.x`? Ant or Maven?

The failure I encountered happens right on startup. It's a OSGi/Felix static dependency wiring, which are only done during startup AFAIK on GF and Payara.

**Comment by stiemannkj1** [comment]
@arjantijms, https://github.com/javaserverfaces/mojarra/commit/7a7dcef00cc573289283ff2e1af1d375aadacd96 should fix the issue. `2.4.x` adds a dependency on the JDK's `javax.annotation.processor` package (which OSGi asssumes is just a subpackage of `javax.annotation`), so I imported that package separately and did not included the version for it.

**Pull request merged**
